line_length:
  warning: 120  # 경고를 발생시킬 최대 길이
  error: 150    # 오류를 발생시킬 최대 길이
  ignores_function_declarations: true  # 함수 선언은 무시
  ignores_comments: true               # 주석은 무시
  ignores_urls: true                   # URL은 무시
